---
- name: Deploy myapp with Ansible
  hosts: my_ec2_group
  become: true

  tasks:
  - name: Install Git
    apt:
      name: git
      state: latest

  - name: Clone myapp repository
    git:
      repo: https://github.com/cloudtechtrainer/8-DevOps-Ansible.git
      dest: /opt/myapp
      version: main
      clone: yes

  - name: Install Python dependencies
    pip:
      requirements: /opt/myapp/requirements.txt

  - name: Start myapp
    command: python /opt/myapp/myapp.py
    async: 10
    poll: 0
    register: myapp_pid

  - name: Wait for myapp to start
    async_status:
      jid: "{{ myapp_pid.ansible_job_id }}"
    register: myapp_result
    until: myapp_result.finished

  - name: Show myapp output
    debug:
      var: myapp_result.stdout_lines
